TOPICS = {
    "Poverty": {
        "keywords": ["poverty", "poor", "income"],
        "indicator": "SI.POV.DDAY",
        "unit": "% of population",
        "description": "Share of people living in extreme poverty",
        "source": "World Bank (SI.POV.DDAY)",
        "methodology": "This indicator measures the share of the population living on less than $2.15 per day in 2011 PPP (Purchasing Power Parity).",
        "source_link": "https://data.worldbank.org/indicator/SI.POV.DDAY",
    },
    "Child Mortality": {
        "keywords": ["child death", "mortality", "infant"],
        "indicator": "SH.DYN.MORT",
        "unit": "deaths per 1,000 live births",
        "description": "Under-5 mortality rate",
        "source": "World Bank (SH.DYN.MORT)",
        "methodology": "This indicator captures the probability of dying before the age of 5, expressed as a rate per 1,000 live births.",
        "source_link": "https://data.worldbank.org/indicator/SH.DYN.MORT",
    },
    "Life Expectancy": {
        "keywords": ["life span", "age", "death"],
        "indicator": "SP.DYN.LE00.IN",
        "unit": "years",
        "description": "Global average life expectancy at birth",
        "source": "World Bank (SP.DYN.LE00.IN)",
        "methodology": "This indicator shows the average number of years a newborn is expected to live, assuming that age-specific mortality rates remain constant.",
        "source_link": "https://data.worldbank.org/indicator/SP.DYN.LE00.IN",
    },
    "Homicide Rate": {
        "keywords": ["violence", "crime", "murder"],
        "indicator": "VC.IHR.PSRC.P5",
        "unit": "per 100,000 people",
        "description": "Intentional homicides (per 100,000 people)",
        "source": "World Bank (VC.IHR.PSRC.P5)",
        "methodology": "This indicator measures the number of deaths caused by intentional violence, expressed as a rate per 100,000 population.",
        "source_link": "https://data.worldbank.org/indicator/VC.IHR.PSRC.P5",
    },
    "Literacy Rate": {
        "keywords": ["education", "reading", "writing", "school"],
        "indicator": "SE.ADT.LITR.ZS",
        "unit": "% of people aged 15+",
        "description": "Adult literacy rate (15+)",
        "source": "World Bank (SE.ADT.LITR.ZS)",
        "methodology": "This indicator shows the percentage of people ages 15 and above who can read and write a short, simple statement.",
        "source_link": "https://data.worldbank.org/indicator/SE.ADT.LITR.ZS",
    },
    "Internet Usage": {
        "keywords": ["internet", "technology", "web access"],
        "indicator": "IT.NET.USER.ZS",
        "unit": "% of population",
        "description": "Individuals using the Internet",
        "source": "World Bank (IT.NET.USER.ZS)",
        "methodology": "Percentage of population that accessed the Internet in the last 12 months.",
        "source_link": "https://data.worldbank.org/indicator/IT.NET.USER.ZS",
    },
    "Access to Electricity": {
        "keywords": ["electricity", "power", "infrastructure"],
        "indicator": "EG.ELC.ACCS.ZS",
        "unit": "% of population",
        "description": "Access to electricity",
        "source": "World Bank (EG.ELC.ACCS.ZS)",
        "methodology": "Percentage of the population with access to electricity.",
        "source_link": "https://data.worldbank.org/indicator/EG.ELC.ACCS.ZS",
    },
    "CO2 Emissions per Capita": {
        "keywords": ["climate", "pollution", "carbon", "emissions"],
        "indicator": "EN.ATM.CO2E.PC",
        "unit": "metric tons per capita",
        "description": "CO2 emissions per capita",
        "source": "World Bank (EN.ATM.CO2E.PC)",
        "methodology": "Carbon dioxide emissions stemming from fossil fuel combustion and industrial processes, divided by population.",
        "source_link": "https://data.worldbank.org/indicator/EN.ATM.CO2E.PC",
    },
    "Clean Water Access": {
        "keywords": ["water", "hygiene", "sanitation"],
        "indicator": "SH.H2O.BASW.ZS",  # Updated and more reliable indicator
        "unit": "% of population",
        "description": "Access to at least basic drinking water services",
        "source": "World Bank (SH.H2O.BASW.ZS)",
        "methodology": "The percentage of population using at least basic drinking water services, including improved water sources that are within a reasonable distance.",
        "source_link": "https://data.worldbank.org/indicator/SH.H2O.BASW.ZS",
    },
    "School Enrollment": {
        "keywords": ["education", "school", "children"],
        "indicator": "SE.PRM.ENRR",
        "unit": "% (gross)",
        "description": "Primary school enrollment (gross)",
        "source": "World Bank (SE.PRM.ENRR)",
        "methodology": "Gross enrollment ratio is the total enrollment in primary education, regardless of age, expressed as a percentage of the population of official primary education age.",
        "source_link": "https://data.worldbank.org/indicator/SE.PRM.ENRR",
    },
    "GDP per Capita": {
        "keywords": ["gdp", "economy", "wealth"],
        "indicator": "NY.GDP.PCAP.CD",
        "unit": "USD",
        "description": "GDP per capita (current US$)",
        "source": "World Bank (NY.GDP.PCAP.CD)",
        "methodology": "Gross domestic product divided by midyear population.",
        "source_link": "https://data.worldbank.org/indicator/NY.GDP.PCAP.CD",
    },
    "Maternal Mortality": {
        "keywords": ["maternal", "pregnancy", "birth", "women's health"],
        "indicator": "SH.STA.MMRT",
        "unit": "deaths per 100,000 live births",
        "description": "Maternal mortality ratio",
        "source": "World Bank (SH.STA.MMRT)",
        "methodology": "Number of women who die from pregnancy-related causes while pregnant or within 42 days of termination per 100,000 live births.",
        "source_link": "https://data.worldbank.org/indicator/SH.STA.MMRT",
    },
    "Immunization Coverage": {
        "keywords": ["vaccination", "measles", "immunization", "health"],
        "indicator": "SH.IMM.MEAS",
        "unit": "% of children ages 12–23 months",
        "description": "Measles immunization coverage among children",
        "source": "World Bank (SH.IMM.MEAS)",
        "methodology": "Percentage of children ages 12–23 months who received one dose of measles-containing vaccine.",
        "source_link": "https://data.worldbank.org/indicator/SH.IMM.MEAS",
    },
    "Gender Parity in Primary School": {
        "keywords": ["gender", "equality", "girls", "education"],
        "indicator": "SE.ENR.PRSC.FM.ZS",
        "unit": "female-to-male ratio",
        "description": "Gender parity index for primary school enrollment",
        "source": "World Bank (SE.ENR.PRSC.FM.ZS)",
        "methodology": "Ratio of girls to boys enrolled at the primary level in public and private schools.",
        "source_link": "https://data.worldbank.org/indicator/SE.ENR.PRSC.FM.ZS",
    },
    "Skilled Health Staff at Birth": {
        "keywords": ["birth", "healthcare", "delivery", "childbirth"],
        "indicator": "SH.STA.BRTC.ZS",
        "unit": "% of births",
        "description": "Births attended by skilled health staff",
        "source": "World Bank (SH.STA.BRTC.ZS)",
        "methodology": "Percentage of live births attended by skilled health personnel (doctor, nurse, or midwife).",
        "source_link": "https://data.worldbank.org/indicator/SH.STA.BRTC.ZS",
    },
    "Undernourishment": {
        "keywords": ["hunger", "nutrition", "food", "undernourishment"],
        "indicator": "SN.ITK.DEFC.ZS",
        "unit": "% of population",
        "description": "Prevalence of undernourishment",
        "source": "World Bank (SN.ITK.DEFC.ZS)",
        "methodology": "Estimated share of the population with insufficient caloric intake.",
        "source_link": "https://data.worldbank.org/indicator/SN.ITK.DEFC.ZS",
    },
    "Renewable Energy Use": {
        "keywords": ["renewable", "energy", "clean", "sustainability"],
        "indicator": "EG.FEC.RNEW.ZS",
        "unit": "% of total energy consumption",
        "description": "Renewable energy consumption",
        "source": "World Bank (EG.FEC.RNEW.ZS)",
        "methodology": "Share of renewable energy in total final energy consumption.",
        "source_link": "https://data.worldbank.org/indicator/EG.FEC.RNEW.ZS",
    },
    "Female Employment in Industry": {
        "keywords": ["employment", "industry", "women", "jobs"],
        "indicator": "SL.IND.EMPL.FE.ZS",
        "unit": "% of female employment",
        "description": "Employment of women in industry",
        "source": "World Bank (SL.IND.EMPL.FE.ZS)",
        "methodology": "The share of employed women working in industrial sectors (manufacturing, mining, construction, utilities).",
        "source_link": "https://data.worldbank.org/indicator/SL.IND.EMPL.FE.ZS",
    },
    "Basic Sanitation Access": {
        "keywords": ["sanitation", "toilets", "hygiene", "infrastructure"],
        "indicator": "SH.STA.BASS.ZS",
        "unit": "% of population",
        "description": "People using at least basic sanitation services",
        "source": "World Bank (SH.STA.BASS.ZS)",
        "methodology": "Percentage of population using improved sanitation facilities that are not shared with other households.",
        "source_link": "https://data.worldbank.org/indicator/SH.STA.BASS.ZS",
    }
}
